import sitemap from "@astrojs/sitemap";
import AxeBuilder from "@axe-core/playwright";
import { compile } from "@mdx-js/mdx";
import { create, insert, load, save, search } from "@orama/orama";
import { chromium } from "@playwright/test";
import tailwindPostcss from "@tailwindcss/postcss";
import { defineConfig as defineAstroConfig } from "astro/config";
import fontkit from "fontkit";
import { defineI18n } from "fumadocs-core/i18n";
import { loader } from "fumadocs-core/source";
import { defineConfig as defineMdxConfig, defineDocs } from "fumadocs-mdx/config";
import { createMDX } from "fumadocs-mdx/next";
import { DocsLayout } from "fumadocs-ui/layouts/docs";
import { RootProvider } from "fumadocs-ui/provider/next";
import lighthouse from "lighthouse";
import type { NextConfig } from "next";
import postcss from "postcss";
import { createElement } from "react";

const database = create({ schema: { title: "string", locale: "string", version: "string" } });
insert(database, { title: "Install", locale: "en", version: "stable" });
const result = search(database, { term: "Install" });
const serialized = save(database);
load(database, serialized);

const nextConfig: NextConfig = { output: "export", images: { unoptimized: true } };
const astroConfig = defineAstroConfig({ output: "static", integrations: [sitemap()] });
const docs = defineDocs({ dir: "content/docs" });
const mdxConfig = defineMdxConfig();
const withMdx = createMDX();
const i18n = defineI18n({ defaultLanguage: "en", languages: ["en", "vi"] });

void AxeBuilder;
void RootProvider;
void DocsLayout;
void astroConfig;
void chromium;
void compile;
void createElement;
void docs;
void fontkit;
void i18n;
void lighthouse;
void loader;
void mdxConfig;
void nextConfig;
void postcss;
void result;
void serialized;
void tailwindPostcss;
void withMdx;
